name: sep490_mobile
description: "Minimal clean app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  dio: ^5.5.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.0
  firebase_auth: ^5.3.1
  firebase_app_check: ^0.3.0+4
  image_picker: ^1.1.2
  intl: ^0.19.0
  google_sign_in: ^6.2.1
  mobile_scanner: ^3.5.7
  url_launcher: ^6.3.0
  video_player: ^2.9.1
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
